project/main/__init__.py
from flask import Blueprint

main_blueprint = Blueprint('main', __name__, template_folder='templates')

from . import views

project/main/views.py
from . import main_blueprint
from flask import render_template, abort, request, flash, current_app, redirect, url_for
from flask_login import login_required, current_user
from project.forms import NewTask, UpdateTask
from project.models import Task
from project import db
from sqlalchemy.exc import IntegrityError

@main_blueprint.route('/')
def index():
    return render_template('main/index.html')


@main_blueprint.route('/tasks', methods=['GET', 'POST'])
@login_required
def tasks():
    form = NewTask()

    tasks = Task.query.order_by(Task.id).filter_by(user_id = current_user.id).all()

    if request.method == 'POST':
        if form.validate_on_submit():

            new_task = Task(form.new_task.data, user_id = current_user.id)
            try:
                db.session.add(new_task)
                db.session.commit()
                flash('New task added!')
                current_app.logger.info('New task added: {}'.format(new_task.id))
                return redirect(url_for('main.tasks'))
            except IntegrityError:
                db.session.rollback()
                flash('Task already exists!')
                current_app.logger.info('Attempt to add task that already exists')
                return redirect(url_for('main.tasks'))
        else:
           flash('Error in the form!')

        
    return render_template('main/tasks.html', form=form, tasks=tasks)

@main_blueprint.route('/delete_task/<int:task_id>')
@login_required
def delete_task(task_id):
    task = Task.query.get(task_id)
    db.session.delete(task)
    db.session.commit()
    flash('Task has been deleted!')
    current_app.logger.info('Task deleted: {}'.format(task_id))
    return redirect(url_for('main.tasks'))

@main_blueprint.route('/mark_complete/<int:task_id>')
@login_required
def mark_complete(task_id):
    task = Task.query.get(task_id)
    task.completed = True
    db.session.add(task)
    db.session.commit()
    flash('Task completed!')
    current_app.logger.info('Task completed: {}'.format(task_id))
    return redirect(url_for('main.tasks'))

@main_blueprint.route('/clear_completed')
@login_required
def clear_completed():
    tasks = Task.query.filter_by(completed=True).all()
    for task in tasks:
        db.session.delete(task)
    db.session.commit()
    flash('Completed list cleared')
    current_app.logger.info('Completed list cleared')
    return redirect(url_for('main.tasks'))


@main_blueprint.route('/update_task/<int:task_id>', methods=['GET', 'POST'])
@login_required
def update_task(task_id):
    task = Task.query.get(task_id)
    form = UpdateTask(updated_task=task.content)
    if request.method == 'POST':
        if form.validate_on_submit():
            task.content = form.updated_task.data
            db.session.add(task)
            db.session.commit()
            flash('Task updated!')
            current_app.logger.info('Task updated: {}'.format(task_id))
            return redirect(url_for('main.tasks'))
        else:
            flash('Error in the form!')
            return redirect(url_for('main.update_task', task_id=task_id))

    return render_template('main/update_task.html', form=form, task=task)


@main_blueprint.route('/500')
def error_500():
    return abort(500)

project/main/templates/main/index.html
{% extends 'bootstrap/base.html'  %} 



{% block title  %}Home{% endblock  %}

{%  block   navbar  %}
{% if current_user.is_authenticated %}
{% include 'navbar_logged_in.html' %}
{% else %}
{% include 'navbar_not_logged_in.html' %}
{% endif %}
{%  endblock  %}

{% block content  %} 
{% include 'flash_messages.html' %}

<div class="container" >
    <div class="col-md-4 col-md-offset-4" >
        <h1 class='text-center'>Task Master</h1>
        <hr>
        <p>A flask application developed using test-driven development principles.</p>
        <p>Keep track of everything you have to do.</p>
        <br>
        <p><a href="{{url_for('auth.register')}}"> Register</a> for an account or <a href="{{url_for('auth.login')}}"> login in</a> and get started enjoying this app!</p>

       
    </div>

    </div>

    {% include 'footer.html' %}

{% endblock  %}



 

project/main/templates/main/tasks.html
{% extends 'bootstrap/base.html'  %} 
{% import 'bootstrap/wtf.html' as wtf %}


{% block title  %}Tasks{% endblock  %}

{%  block   navbar  %}
{% if current_user.is_authenticated %}
{% include 'navbar_logged_in.html' %}
{% else %}
{% include 'navbar_not_logged_in.html' %}
{% endif %}
{%  endblock  %}

{% block content    %}
{% include 'flash_messages.html' %}
<div class='container'>
    <div class='text-center h1 text-white bg-primary'>Add a new task</div>
    <form action="" method="post" class="form" role="form" >
        {{ form.hidden_tag() }}
    
        <div class="form-group ">
        {{ wtf.form_field(form.new_task, type='text', class='form-control', placeholder='Task') }}
        </div>   
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <hr>
    <div class='row'>
        
        <div class='col-md-6'>
            <div class='text-center h1 text-white bg-primary'>To do</div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <td>Task</td>
                            <td>Date Created</td>
                            <td>Action</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                        {% if not task.completed%}
                        <tr>
                            <td>{{task.content}}</td>
                            <td>{{task.date_created.strftime("%Y-%m-%d")}}</td>
                            <td><a href="{{ url_for('main.delete_task', task_id= task.id) }}">Delete</a><br><a href="{{ url_for('main.update_task', task_id= task.id) }}">Update</a><br><a href="{{ url_for('main.mark_complete', task_id= task.id) }}">Mark as complete</a></td>
                        </tr>
                        {%  endif   %}
                        {%  endfor  %}


                    </tbody>
                  
                </table>
              </div>

            <div>
                

            </div>
            
            

        </div>
        <div class='col-md-6'>
            <div class='text-center h1 text-white bg-primary'>Completed tasks</div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <td>Task</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                        {% if task.completed%}
                        <tr>
                            <td>{{task.content}}</td>
                        </tr>
                        {%  endif   %}
                        {%  endfor  %}


                    </tbody>
                  
                </table>
                <p><a href="{{ url_for('main.clear_completed') }}">Clear completed tasks list</a></p>
              </div>

        </div>
    </div>
</div>
{% include 'footer.html' %}
{%  endblock    %}

project/main/templates/main/update_task.html
{% extends 'bootstrap/base.html'  %} 
{% import 'bootstrap/wtf.html' as wtf  %} 


{% block title  %}Update Task{% endblock  %}

{%  block   navbar  %}
{% if current_user.is_authenticated %}
{% include 'navbar_logged_in.html' %}
{% else %}
{% include 'navbar_not_logged_in.html' %}
{% endif %}
{%  endblock  %}

{% block content  %} 
{% include 'flash_messages.html' %}


<div class="container" >
    <div class="col-md-4 col-md-offset-4" >
        <div class='text-center h1 text-white bg-primary' style='padding:10px 0px;'>Update Task</div>
        <hr>
        <form action="" method="post" class="form" role="form" >
            {{ form.hidden_tag() }}
        
            <div class="form-group ">
            {{ wtf.form_field(form.updated_task, type='text', class='form-control') }}
            </div>   
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    </div>
    {% include 'footer.html' %}

{% endblock  %}